<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kategori_item extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kategori_item_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'kategori_item/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'kategori_item/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'kategori_item/index.html';
            $config['first_url'] = base_url() . 'kategori_item/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Kategori_item_model->total_rows($q);
        $kategori_item = $this->Kategori_item_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'kategori_item_data' => $kategori_item,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('kategori_item/kategori_item_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Kategori_item_model->get_by_id($id);
        if ($row) {
            $data = array(
		'nama_item' => $row->nama_item,
		'nama_kategori' => $row->nama_kategori,
	    );
            $this->load->view('kategori_item/kategori_item_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_item'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kategori_item/create_action'),
	    'nama_item' => set_value('nama_item'),
	    'nama_kategori' => set_value('nama_kategori'),
	);
        $this->load->view('kategori_item/kategori_item_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Kategori_item_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('kategori_item'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kategori_item_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kategori_item/update_action'),
		'nama_item' => set_value('nama_item', $row->nama_item),
		'nama_kategori' => set_value('nama_kategori', $row->nama_kategori),
	    );
            $this->load->view('kategori_item/kategori_item_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_item'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('nama_item', TRUE));
        } else {
            $data = array(
	    );

            $this->Kategori_item_model->update($this->input->post('nama_item', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kategori_item'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kategori_item_model->get_by_id($id);

        if ($row) {
            $this->Kategori_item_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kategori_item'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_item'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('nama_item', 'nama_item', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kategori_item.php */
/* Location: ./application/controllers/Kategori_item.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-25 19:55:08 */
/* http://harviacode.com */