<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang_model extends CI_Model
{

    public $table = 'barang';
    public $id = 'id_barang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('pengguna', 'pengguna.no_ktp=no_ktp_penyewa');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_review($id)
    {
        $this->db->join('barang_dikirim', 'barang_dikirim on barang.id_barang=barang_dikirim.id_barang');
        $this->db->join('pengguna', 'no_ktp_penyewa=no_ktp');
        $this->db->where('barang.id_barang', $id);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL, $level=NULL) {
        $this->db->join('info_barang_level','barang.id_barang=info_barang_level.id_barang');
        $this->db->like('barang.id_barang', $q);
	$this->db->or_like('nama_item', $q);
	$this->db->or_like('warna', $q);
	$this->db->or_like('url_foto', $q);
	$this->db->or_like('kondisi', $q);
	// $this->db->or_like('lama_penggunaan', $q);
	$this->db->or_like('no_ktp_penyewa', $q);
    $this->db->where('info_barang_level.nama_level',$level);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $level=NULL) {
        $this->db->join('info_barang_level','barang.id_barang=info_barang_level.id_barang');
        $this->db->order_by('barang.'.$this->id, $this->order);
        $this->db->like('barang.id_barang', $q);
	$this->db->or_like('nama_item', $q);
	$this->db->or_like('warna', $q);
	$this->db->or_like('url_foto', $q);
	$this->db->or_like('kondisi', $q);
	// $this->db->or_like('lama_penggunaan', $q);
	$this->db->or_like('no_ktp_penyewa', $q);
    $this->db->where('info_barang_level.nama_level',$level);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Barang_model.php */
/* Location: ./application/models/Barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-25 19:55:08 */
/* http://harviacode.com */