<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang_dikirim_model extends CI_Model
{

    public $table = 'barang_dikirim';
    public $id = 'no_resi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL,$penyewa=NULL) {
        $this->db->join('barang','barang.id_barang=barang_dikirim.id_barang');
        $this->db->join('pengiriman','barang_dikirim.no_resi=pengiriman.no_resi');
        $this->db->join('pemesanan','pemesanan.id_pemesanan=pengiriman.id_pemesanan');
        $this->db->like('barang_dikirim.no_resi', $q);
	$this->db->or_like('barang_dikirim.id_barang', $q);
	// $this->db->or_like('tanggal_review', $q);
	$this->db->or_like('review', $q);
    $this->db->or_like('no_ktp_pemesan', $penyewa);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    


    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL,$penyewa=NULL) {
        $this->db->join('barang','barang.id_barang=barang_dikirim.id_barang');
        $this->db->join('pengiriman','barang_dikirim.no_resi=pengiriman.no_resi');
        $this->db->join('pemesanan','pemesanan.id_pemesanan=pengiriman.id_pemesanan');
        $this->db->order_by('barang_dikirim.'.$this->id, $this->order);
        $this->db->like('barang_dikirim.no_resi', $q);
	$this->db->or_like('barang_dikirim.id_barang', $q);
	// $this->db->or_like('tanggal_review', $q);
	$this->db->or_like('review', $q);
    $this->db->or_like('no_ktp_pemesan', $penyewa);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Barang_dikirim_model.php */
/* Location: ./application/models/Barang_dikirim_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-25 19:55:08 */
/* http://harviacode.com */