<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Item_model extends CI_Model
{

    public $table = 'item';
    public $id = 'nama';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    function get_by_level($level=NULL)
    {
        $this->db->join('barang', 'barang.nama_item=item.nama');
        $this->db->join('info_barang_level', 'barang.id_barang=info_barang_level.id_barang');
        $this->db->where('nama_level', $level);
        return $this->db->get($this->table);
    }
    // get total rows
    function total_rows($q = NULL) {
        $this->db->join('kategori_item', 'kategori_item.nama_item=item.nama');
        $this->db->like('nama', $q);
	$this->db->or_like('deskripsi', $q);
	// $this->db->or_like('usia_dari', $q);
	// $this->db->or_like('usia_sampai', $q);
	$this->db->or_like('bahan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->join('kategori_item', 'kategori_item.nama_item=item.nama');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('nama', $q);
	$this->db->or_like('deskripsi', $q);
	// $this->db->or_like('usia_dari', $q);
	// $this->db->or_like('usia_sampai', $q);
	$this->db->or_like('bahan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }


    function total_rows_home($q = NULL,$level=NULL) {
        $this->db->join('barang', 'barang.nama_item=item.nama');
        $this->db->join('info_barang_level', 'barang.id_barang=info_barang_level.id_barang');
        
        // $this->db->like('nama', $q);
        // $this->db->or_like('deskripsi', $q);
        // $this->db->or_like('usia_dari', $q);
        // $this->db->or_like('usia_sampai', $q);
        // $this->db->or_like('bahan', $q);
        $this->db->where('nama_level', $level);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data_home($limit, $start = 0, $q = NULL,$level=NULL) {
        $this->db->join('barang', 'barang.nama_item=item.nama');
        $this->db->join('info_barang_level', 'barang.id_barang=info_barang_level.id_barang');
        
        $this->db->order_by($this->id, $this->order);
        // $this->db->like('nama', $q);
    // $this->db->or_like('deskripsi', $q);
    // $this->db->or_like('usia_dari', $q);
    // $this->db->or_like('usia_sampai', $q);
    // $this->db->or_like('bahan', $q);
    $this->db->where('nama_level', $level);
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Item_model.php */
/* Location: ./application/models/Item_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-25 19:55:08 */
/* http://harviacode.com */